### PR TITLE
Responsive site

### PR DESCRIPTION
**Pull request by merodriguezblanco**
@grayghostvisuals as discussed in #65, this pull request is into development branch.

### CODE REVIEW

**Comment by grayghostvisuals** [comment]
I'm gonna let this marinate for a bit until I can review more. Been busy with paying work ATM :)

**Comment by grayghostvisuals** [comment]
Since this is not really a pressing feature ATM would you mind spending a little more time on the structure of it? Not a fan of the blanketing media queries and I think the organization can use some work as well.

a few more thoughts…
- code blocks font-sizing becomes too small as viewport width decreases
- I think we can find another way to stack those nav items rather than columnar. I'll let you be creative there.
- Logo sizing can be adjusted. It's a bit big (even the text that is a part of it). I might even consider adjusting that size in larger views too.
- Need to conditionally load the GitHub script for contributors.

Overall a good start though! Keep up the great progress and let me know when you have an update and I'll take another look. :metal:

**Comment by merodriguezblanco** [comment]
Thanks for your feedback! Are you still planning to consider the responsive version primarily for developers on desktop?

**Comment by grayghostvisuals** [comment]
> Are you still planning to consider the responsive version primarily for developers on desktop? 

Confused? I think you mean do i consider this project to be geared at developers using desktop than the answer is yes.

**Comment by grayghostvisuals** [comment]
Closing for now, but thanks for the efforts here. Maybe we'll revisit this soon.

**Pull request closed without merging**
