### PR TITLE
removing git protocol from assemble dependency

### PR DESCRIPTION
**Pull request by doowb**

### CODE REVIEW

**Comment by grayghostvisuals** [comment]
Gracias DoooooooB!

**Comment by jfroffice** [comment]
@doowb :+1:

**Comment by jfroffice** [comment]
Does not seem to work on my side.
```
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/assemble/assemble)
npm ERR! git clone git@github.com:assemble/assemble ssh: connect to host github.com port 22: Bad file number
npm ERR! git clone git@github.com:assemble/assemble fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:assemble/assemble
npm ERR! git clone git@github.com:assemble/assemble Please make sure you have the correct access rights
npm ERR! git clone git@github.com:assemble/assemble and the repository exists.
```

**Comment by grayghostvisuals** [comment]
@jfroffice Check your network settings.

**Comment by jfroffice** [comment]
Check my network

It only allows ```http://``` or ```https//``` meaning port 80 or 443 failed :confused:

**Pull request merged**
