### PR TITLE
Search icon

### PR DESCRIPTION
**Pull request by brouxhaha**
Added search icon that changes to X.

### CODE REVIEW

**Comment by grayghostvisuals** [comment]
Do you think there's a better used term we can use to catalog this type of icon instead of “search?” 
I was thinking a few ideas… 

- inputs
- location
- forms
- retrieval/information

Thoughts? Also have you given a shot using SVG instead of CSS? Just an idea. Maybe a good one to try for another variation at a later time.

**Comment by brouxhaha** [comment]
There may be a better way to represent it, but I was really going off what the other icons were called. It's essentially the same as the menu buttons since it would show a hidden search box/button.

SVG is what I wanted to do initially, but I was having trouble finding SVG animated icons. I actually thought that's what Transformicons used until I looked into them. I'd definitely like to move this to SVG.

**Comment by grayghostvisuals** [comment]
Out of the names I listed previously which one do you think sounds better?

> I was having trouble finding SVG animated icons

Where were you looking? The project itself?

>I actually thought that's what Transformicons used until I looked into them

The project does accept SVG and another reason why I'm pushing with it because it lacks any presence of SVG ATM and I'd like to see it represented. Thats why it might be another good one for you to try or even someone else. Not saying you can't submit this one.

**Comment by brouxhaha** [comment]
I think forms or retrieval/information make the most sense. It'll be use to show a form; it'll allow the user to retrieve information. 

I was just doing a general search and looking on Codepen, but I may have limited that to animated search icon - which lead me back to Transformicons to see how those were built. I'll need to broaden my search to find some examples.

If I get some time this weekend, I'll look into animated SVG icons and see if I can bust something out. It may be worth having both css and SVG icons for all of them.

**Pull request merged**
