### PR TITLE
Remove dotted outline from icons.

### PR DESCRIPTION
**Pull request by merodriguezblanco**
Solves #36

### CODE REVIEW

**Comment by grayghostvisuals** [comment]
see [9655ba5df](https://github.com/grayghostvisuals/transformicons/commit/9655ba5df482f7ea86e456fdee78655aea7a6a57)

**Comment by merodriguezblanco** [comment]
@grayghostvisuals  the idea behind this PR was to remove the dotted border when the tcons are focused on Firefox. I've seen that Firefox adds an inner border to the <button> elements when focusing using the tab key (this doesn't happen on other browsers).

**Comment by grayghostvisuals** [comment]
I have not pushed this live yet if thats what you're referring to. see the commit hash I linked to above. It's merged into development for the moment.

**Comment by merodriguezblanco** [comment]
Got it, I was just trying to make clear that I was not trying to solve the original issue about the dotted borders around the icons on all browsers, but just to remove that behavior on Firefox when focusing them. I forgot to add a description to the PR on the first place, sorry!

**Pull request closed without merging**
