### PR TITLE
Add "del" module on all environments.

### PR DESCRIPTION
**Pull request by merodriguezblanco**

### CODE REVIEW

**Comment by grayghostvisuals** [comment]
Why would the del module be triggering an error? This is still identical to the previously deployed code that had no problems whatsoever so I'm wondering why all of a sudden you think it's the del module?

**Comment by merodriguezblanco** [comment]
Would you mind please pasting here your heroku logs after the deploy? My logs were throwing the error: ``Error: Cannot find module 'del'`` after deploying. The ``del`` module was being included only on development environment, and it is being used in the gulpfile for some tasks such as cleaning.

**Comment by grayghostvisuals** [comment]
Logs say nothing in regards to any errors. When you say “deploy” it is much different process then I do when sending code to Heroku. package.json controls what modules are installed for what env and del is only needed when developing locally.

**Comment by merodriguezblanco** [comment]
Yes, I have mistakenly thought that the ``del`` module was being used on the gulpfile for the production environment. The reason for that confusion was that heroku logged me an error for the missing ``del`` module. :S

Anyway, good news that you have found what was causing the problem! Sorry for the the wrong answer!

**Pull request closed without merging**
