### PR TITLE
Responsive site

### PR DESCRIPTION
**Pull request by merodriguezblanco**
Responsive look and feel for the site #31 .

### CODE REVIEW

**Comment by grayghostvisuals** [comment]
@merodriguezblanco Can you do me a favor and put this into one commit and also send me this PR to the development branch? appreciate it :metal:

**Comment by blancolinka** [comment]
@grayghostvisuals Why don't you just merge it in the development branch? Squashing commits while merging is like 10 characters more to type, come-on, don't be lazy :)

**Comment by grayghostvisuals** [comment]
@blancolinka You make a good point and since you asked so nicely I'll go with your suggestion ;)

**Comment by arthurvr** [comment]
Closing in favor of #66

**Pull request closed without merging**
